---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1579558/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp -R dist $DEPLOYPATH
    - /bin/cp -R src $DEPLOYPATH
