---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1579558/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp tailwind.config.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -r dist $DEPLOYPATH
    - /bin/cp -r src $DEPLOYPATH
